package cross

import (
	"fmt"
	"sort"
	"strings"
)

// GenerateScute converts a CrossResult into a complete, ready-to-review .scute file.
func GenerateScute(result *CrossResult, projectName, workspace string) string {
	var sb strings.Builder

	mapped := result.Mapped()
	unmapped := result.UnmappedResources()

	// ── Header ──────────────────────────────────────────────────────────────────
	sb.WriteString("# Generated by gecko cross\n")
	sb.WriteString(fmt.Sprintf("# Source:    %s (%s)\n", result.Kind, result.SourceFile))
	if result.ToolVersion != "" {
		sb.WriteString(fmt.Sprintf("# Version:   %s\n", result.ToolVersion))
	}
	sb.WriteString(fmt.Sprintf("# Imported:  %s\n", result.ImportedAt.Format("2006-01-02T15:04:05Z")))
	sb.WriteString(fmt.Sprintf("# Resources: %d mapped, %d unmapped\n", len(mapped), len(unmapped)))
	sb.WriteString("#\n")
	sb.WriteString("# Review this file before running gecko grip.\n")
	sb.WriteString("# Remove any resources you do not want Gecko to manage.\n")
	sb.WriteString("\n")

	// ── Territory ───────────────────────────────────────────────────────────────
	sb.WriteString(fmt.Sprintf("territory %q\n", projectName))
	sb.WriteString(fmt.Sprintf("  workspace: %q\n", workspace))
	sb.WriteString("end\n\n")

	// ── Habitat blocks — one per detected provider ────────────────────────────
	for _, prov := range detectProviders(mapped) {
		sb.WriteString(renderHabitat(prov))
		sb.WriteString("\n")
	}

	// ── Spawn blocks grouped by Gecko type ────────────────────────────────────
	if len(mapped) > 0 {
		groups := groupByGeckoType(mapped)
		for _, geckoType := range sortedStringKeys(groups) {
			pad := 60 - len(geckoType)
			if pad < 0 {
				pad = 0
			}
			sb.WriteString(fmt.Sprintf("# ── %s %s\n\n", geckoType, strings.Repeat("─", pad)))
			for _, res := range groups[geckoType] {
				sb.WriteString(renderSpawn(res))
				sb.WriteString("\n")
			}
		}
	}

	// ── Unmapped resources as commented-out blocks ────────────────────────────
	if len(unmapped) > 0 {
		sb.WriteString(strings.Repeat("─", 79) + "\n")
		sb.WriteString("# Unmapped resources — no Gecko provider handles these types.\n")
		sb.WriteString("# They are preserved here for reference. To manage them, either:\n")
		sb.WriteString("#   • Build a custom provider (see: gecko Building Providers)\n")
		sb.WriteString("#   • Run gecko burrow to import them once managed elsewhere\n")
		sb.WriteString(strings.Repeat("─", 79) + "\n\n")
		for _, res := range unmapped {
			sb.WriteString(renderUnmapped(res))
			sb.WriteString("\n")
		}
	}

	return sb.String()
}

func renderHabitat(provider string) string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("habitat %q\n", provider))
	switch provider {
	case "k8s":
		sb.WriteString("  kubeconfig: \"~/.kube/config\"\n")
		sb.WriteString("  # context: \"my-context\"\n")
	case "vault":
		sb.WriteString("  address: env(\"VAULT_ADDR\")\n")
		sb.WriteString("  token:   secret(\"vault.token\")\n")
	case "nomad":
		sb.WriteString("  address: env(\"NOMAD_ADDR\")\n")
		sb.WriteString("  # token: secret(\"nomad.token\")\n")
	case "gitea":
		sb.WriteString("  url:   env(\"GITEA_URL\")\n")
		sb.WriteString("  token: secret(\"gitea.token\")\n")
	case "minio":
		sb.WriteString("  endpoint:   env(\"MINIO_ENDPOINT\")\n")
		sb.WriteString("  access_key: secret(\"minio.access_key\")\n")
		sb.WriteString("  secret_key: secret(\"minio.secret_key\")\n")
	case "postgresql":
		sb.WriteString("  host:     env(\"PG_HOST\")\n")
		sb.WriteString("  port:     5432\n")
		sb.WriteString("  username: env(\"PG_USER\")\n")
		sb.WriteString("  password: secret(\"postgresql.password\")\n")
	}
	sb.WriteString("end\n")
	return sb.String()
}

func renderSpawn(res *ImportedResource) string {
	var sb strings.Builder

	// Provenance comment
	src := fmt.Sprintf("# imported from: %s.%s", res.SourceType, res.Name)
	if res.Module != "" {
		src += fmt.Sprintf("  (module: %s)", res.Module)
	}
	sb.WriteString(src + "\n")
	if res.ExternalID != "" {
		sb.WriteString(fmt.Sprintf("# external id:   %s\n", res.ExternalID))
	}

	sb.WriteString(fmt.Sprintf("spawn %q as %q\n", res.GeckoType, res.Name))
	for _, k := range sortedStringKeys(res.Inputs) {
		sb.WriteString(renderField(k, res.Inputs[k], 1))
	}
	sb.WriteString("end\n")
	return sb.String()
}

func renderUnmapped(res *ImportedResource) string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("# spawn ??? as %q\n", res.Name))
	sb.WriteString(fmt.Sprintf("#   source_type: %q\n", res.SourceType))
	if res.ExternalID != "" {
		sb.WriteString(fmt.Sprintf("#   external_id: %q\n", res.ExternalID))
	}
	if res.Module != "" {
		sb.WriteString(fmt.Sprintf("#   module:      %q\n", res.Module))
	}
	sb.WriteString("# end\n")
	return sb.String()
}

// renderField recursively renders a key: value pair in Scute syntax.
func renderField(key string, val interface{}, depth int) string {
	indent := strings.Repeat("  ", depth)

	switch v := val.(type) {
	case string:
		return fmt.Sprintf("%s%s: %q\n", indent, key, v)

	case float64:
		if v == float64(int64(v)) {
			return fmt.Sprintf("%s%s: %d\n", indent, key, int64(v))
		}
		return fmt.Sprintf("%s%s: %g\n", indent, key, v)

	case bool:
		return fmt.Sprintf("%s%s: %v\n", indent, key, v)

	case nil:
		return "" // omit null fields

	case map[string]interface{}:
		if len(v) == 0 {
			return ""
		}
		var sb strings.Builder
		sb.WriteString(fmt.Sprintf("%s%s:\n", indent, key))
		for _, k := range sortedStringKeys(v) {
			sb.WriteString(renderField(k, v[k], depth+1))
		}
		sb.WriteString(fmt.Sprintf("%send\n", indent))
		return sb.String()

	case []interface{}:
		if len(v) == 0 {
			return ""
		}
		// Scalar list → inline array syntax
		if allScalars(v) {
			parts := make([]string, 0, len(v))
			for _, el := range v {
				parts = append(parts, scuteScalar(el))
			}
			return fmt.Sprintf("%s%s: [%s]\n", indent, key, strings.Join(parts, ", "))
		}
		// List of objects → sub-block per element
		var sb strings.Builder
		sb.WriteString(fmt.Sprintf("%s%s:\n", indent, key))
		for _, el := range v {
			if m, ok := el.(map[string]interface{}); ok {
				for _, k := range sortedStringKeys(m) {
					sb.WriteString(renderField(k, m[k], depth+1))
				}
			}
		}
		sb.WriteString(fmt.Sprintf("%send\n", indent))
		return sb.String()
	}

	return fmt.Sprintf("%s%s: %v\n", indent, key, val)
}

func allScalars(v []interface{}) bool {
	for _, el := range v {
		switch el.(type) {
		case string, float64, bool:
		default:
			return false
		}
	}
	return true
}

func scuteScalar(v interface{}) string {
	switch val := v.(type) {
	case string:
		return fmt.Sprintf("%q", val)
	case float64:
		if val == float64(int64(val)) {
			return fmt.Sprintf("%d", int64(val))
		}
		return fmt.Sprintf("%g", val)
	case bool:
		return fmt.Sprintf("%v", val)
	}
	return fmt.Sprintf("%v", v)
}

// detectProviders returns sorted unique provider prefixes from a set of resources.
func detectProviders(resources []*ImportedResource) []string {
	seen := make(map[string]bool)
	for _, r := range resources {
		if p := providerPrefix(r.GeckoType); p != "" {
			seen[p] = true
		}
	}
	result := make([]string, 0, len(seen))
	for p := range seen {
		result = append(result, p)
	}
	sort.Strings(result)
	return result
}

func providerPrefix(geckoType string) string {
	if i := strings.Index(geckoType, ":"); i >= 0 {
		return geckoType[:i]
	}
	return geckoType
}

func groupByGeckoType(resources []*ImportedResource) map[string][]*ImportedResource {
	groups := make(map[string][]*ImportedResource)
	for _, r := range resources {
		groups[r.GeckoType] = append(groups[r.GeckoType], r)
	}
	return groups
}

func sortedStringKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
